# Generated by Django 4.2 on 2023-04-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_remove_movielist_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='genre',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movielist',
            name='img',
            field=models.ImageField(default='ddd', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
